# Generated by Django 6.0.2 on 2026-04-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/', verbose_name='Фото'),
        ),
    ]
