# Generated by Django 6.0.2 on 2026-03-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_reopen',
            field=models.BooleanField(default=False, verbose_name='Переоткрывалась ли'),
        ),
    ]
