# Generated by Django 6.0.2 on 2026-04-12 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_attachments_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='task_manager.tasks', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task_manager.tasks', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_detail', to='task_manager.projects', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tasks',
            field=models.ManyToManyField(related_name='tags', to='task_manager.tasks', verbose_name='Задачи'),
        ),
    ]
