# Generated by Django 6.0.2 on 2026-04-15 11:36

import task_manager.models.attachments
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_attachments_file_alter_attachments_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', validators=[task_manager.models.attachments.validate_file_size, task_manager.models.attachments.validate_file_type], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/', validators=[task_manager.models.attachments.validate_file_size], verbose_name='Фото'),
        ),
    ]
