# Generated by Django 6.0.2 on 2026-04-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_attachments_file_alter_attachments_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
