# Generated by Django 6.0.2 on 2026-05-29 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_alter_tasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO')], default='FIFO', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='task_manager.tasks')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('task', 'strategy'), name='unique_task_per_strategy')],
            },
        ),
    ]
